### ISSUE TITLE
Scrolling not working

### ISSUE THREAD

**Issue by FANMixco** [rofiqsetiawan/OneMoreFabMenuDemo#1]
Hi Rofiq,

There was a minor change from André because I discovered a couple of days ago that the scroll didn't work on the same column where was the button; also, the click was nullified in that section. Thanks for your great work!

**Comment by rofiqsetiawan** [comment]
I've just updated it to v1.0.3.
So far I don't find non-clickable-area bug again with simple button on top of ListView.

Please let me know your result 😊

**Comment by FANMixco** [comment]
Hi Rofiq!

Thanks, it's working! The issue happened when you were not using a ListView, but for example buttons or other controls.
